### ISSUE TITLE
SQLite3 support for Refined's source

### ISSUE THREAD

**Issue by mhs02** [emisandgunz/GunzCord#1]
Some servers run RefinedGunz source.
Refined is defaulted to use Sqlite3 as there database.

The Refined matchserver auto generates an Sqlite3 database if not found in its working directory.

Old versions of GunzCord had Sqlite3 support for Refined, we should continue to support this, expanding the use of the bot.

**Comment by emisandgunz** [comment]
I will work on it soon. Please note that as I don't run a sqlite based Gunz server I won't be able to do extensive testing, but will use the Refined Gunz files to do the basic testing
